[font]
size = 18

[font.bold]
style = "bold"

[font.bold_italic]
style = "bold italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
style = "italic"

[font.normal]
family = "BlexMono Nerd Font"
style = "regular"

[font.offset]
x = 0
y = 0
